### ISSUE TITLE
[BUG] nil pointer values are encoded as "null" and not decodable

### ISSUE THREAD

**Issue by david-its** [gorilla/schema#217] opened 2024-08-16 19:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it seems that optional fields using pointers to values are not handled by schema properly. e.g.:
```
        type S struct {
                Flag *bool `schema:"flag"`
        }
```

if we encode such an empty struct `S{}` it will result in ` url.Values{"flag": []string{"null"}}`, which is not decodable by schema. The solution is to use `omitempty`. But it is easy to miss that. Can we panic on such fields to make sure omitempty is not missing? Another option is to handle correctly "null" values on decode.

Opinion?

### Expected Behavior

Correctly encode/decode on empty struct with pointers.

**Comment by jaitaiwan** [comment] 2024-08-20 13:34
Going to close this as a duplicate of #216

**Closed as completed by jaitaiwan** 2024-08-20 13:34 UTC
Labels: bug
